export const tutors = [
  {
    id: '1',
    name: 'Dr. Evelyn Reed',
    avatar: 'https://placehold.co/100x100.png',
    subjects: ['Physics', 'Calculus', 'Mathematics'],
    bio: 'PhD in Physics with 10+ years of teaching experience at the university level. I make complex topics easy to understand.',
    rating: 4.9,
    price: 75,
  },
  {
    id: '2',
    name: 'Samuel Chen',
    avatar: 'https://placehold.co/100x100.png',
    subjects: ['Computer Science', 'Python', 'Mathematics'],
    bio: 'Software Engineer at a top tech company. Passionate about teaching programming to beginners and advanced students.',
    rating: 5.0,
    price: 60,
  },
  {
    id: '3',
    name: 'Maria Garcia',
    avatar: 'https://placehold.co/100x100.png',
    subjects: ['Spanish', 'French'],
    bio: 'Native Spanish speaker and certified language instructor. Let\'s make learning a new language fun and interactive!',
    rating: 4.8,
    price: 45,
  },
    {
    id: '4',
    name: 'Ben Carter',
    avatar: 'https://placehold.co/100x100.png',
    subjects: ['History', 'Literature'],
    bio: 'History buff with a Master\'s degree. I help students develop critical thinking and essay writing skills.',
    rating: 4.9,
    price: 50,
  },
  {
    id: '5',
    name: 'Aisha Khan',
    avatar: 'https://placehold.co/100x100.png',
    subjects: ['Biology', 'Chemistry'],
    bio: 'Medical student with a passion for the sciences. I specialize in test prep and breaking down difficult concepts.',
    rating: 4.9,
    price: 55,
  },
  {
    id: '6',
    name: 'Kenji Tanaka',
    avatar: 'https://placehold.co/100x100.png',
    subjects: ['Art', 'Design', 'Physics'],
    bio: 'Professional graphic designer helping students build their creative portfolios and master design software.',
    rating: 5.0,
    price: 65,
  },
  {
    id: '7',
    name: 'Dr. Raj Patel',
    avatar: 'https://placehold.co/100x100.png',
    subjects: ['Chemistry', 'Biology'],
    bio: 'Former professor with a knack for making organic chemistry understandable. NEET specialist.',
    rating: 4.9,
    price: 80,
  },
   {
    id: '8',
    name: 'Mei Lin',
    avatar: 'https://placehold.co/100x100.png',
    subjects: ['Mathematics', 'Physics'],
    bio: 'IIT graduate with a passion for helping students excel in JEE Mains and Advanced.',
    rating: 5.0,
    price: 85,
  },
];
